# Generated by Django 2.2.9 on 2020-01-18 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_workplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplace',
            name='ceo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.User'),
        ),
    ]
