# Generated by Django 2.2.9 on 2020-01-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200118_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jobs',
            field=models.ManyToManyField(to='home.WorkPlace'),
        ),
    ]
