# Generated by Django 2.2.9 on 2020-01-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_user_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jobs',
            field=models.ManyToManyField(related_name='users', to='home.WorkPlace'),
        ),
    ]
