# Generated by Django 2.2.9 on 2020-01-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='jobs',
        ),
        migrations.RemoveField(
            model_name='workplace',
            name='ceo',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='WorkPlace',
        ),
    ]
