# Generated by Django 2.2.9 on 2020-01-29 08:30

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20200129_0828'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.UniqueConstraint(condition=models.Q(('acceptant', django.db.models.expressions.F('initiator')), ('initiator', django.db.models.expressions.F('acceptant'))), fields=('initiator', 'acceptant'), name='chat_unique_constraint'),
        ),
    ]
