# Generated by Django 2.2.9 on 2020-01-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_auto_20200129_0830'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chat',
            name='chat_unique_constraint',
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.UniqueConstraint(fields=('initiator', 'acceptant'), name='chat_unique_constraint'),
        ),
    ]
